import type { SupabaseClient } from "@supabase/supabase-js";

/**
 * Every query the app makes, against Supabase.
 *
 * Each takes the client rather than reaching for a module-level one, because
 * there are two: the signed-in user's (RLS applies) for anything a person
 * did, and the service-role client for the scraper, which has no person
 * behind it. Passing it in is what keeps that choice visible at the call
 * site instead of hidden in here.
 */
export type Db = SupabaseClient;

export const STATUSES = ["new", "applied", "dismissed"] as const;
export type Status = (typeof STATUSES)[number];

export type JobRow = {
  id: number;
  source: string;
  title: string;
  company: string | null;
  location: string | null;
  salary: string | null;
  url: string;
  snippet: string | null;
  posted_at: string;
  fetched_at: string;
  status: Status;
  notes: string | null;
  manual: boolean;
};

/**
 * Same job posted on several boards: match on company + title, ignoring
 * punctuation and the noise boards add ("Remote", "100%", "Inc").
 *
 * Unchanged from the SQLite version, deliberately — the keys already in the
 * database were generated by it, and a "better" normaliser would fail to
 * match every row written before it.
 */
export function dedupeKey(company = "", title = ""): string {
  const norm = (s: string) =>
    s
      .toLowerCase()
      .replace(/\(.*?\)|\[.*?\]/g, " ")
      .replace(/\b(remote|us|usa|united states|100%|fully|work from home)\b/g, " ")
      .replace(/\b(inc|llc|ltd|corp|corporation|co)\b\.?/g, " ")
      .replace(/[^a-z0-9+#]+/g, " ")
      .trim();
  return `${norm(company)}|${norm(title)}`;
}

const LIST_COLUMNS =
  "id, source, title, company, location, salary, url, snippet, posted_at, fetched_at, status, notes, manual";

/** Fields a person may edit. Listed, so a column added later is not writable by accident. */
const EDITABLE = [
  "title",
  "company",
  "location",
  "salary",
  "url",
  "description",
  "posted_at",
  "status",
  "notes",
] as const;

// ---------------------------------------------------------------- reading

export async function listJobs(
  db: Db,
  {
    status = "active",
    source,
    q,
    limit = 500,
    offset = 0,
  }: { status?: string; source?: string; q?: string; limit?: number; offset?: number } = {},
) {
  // The view carries the 400-character snippet; see supabase/schema.sql for
  // why that truncation is in Postgres rather than here.
  // Explicit columns: the view also carries `description` so the search can
  // filter on it, and selecting `*` would ship all 5 KB of it per row.
  let query = db
    .from("search_job_list")
    .select(LIST_COLUMNS, { count: "exact" })
    .order("posted_at", { ascending: false })
    .order("id", { ascending: false })
    .range(offset, offset + limit - 1);

  if (status === "active") query = query.neq("status", "dismissed");
  else if (status && status !== "all") query = query.eq("status", status);
  if (source) query = query.eq("source", source);

  if (q) {
    // `or` takes one string, and a comma or parenthesis inside the term would
    // be read as PostgREST syntax — so those are stripped rather than
    // escaped, which keeps the filter a filter and not an injection point.
    const safe = q.replace(/[(),*"']/g, " ").trim();
    if (safe) {
      const like = `*${safe}*`;
      query = query.or(
        `title.ilike.${like},company.ilike.${like},description.ilike.${like}`,
      );
    }
  }

  const { data, error, count } = await query;
  if (error) throw new Error(error.message);
  return { total: count ?? 0, jobs: (data ?? []) as JobRow[] };
}

export async function getJob(db: Db, id: number) {
  const { data, error } = await db
    .from("search_job")
    .select("*")
    .eq("id", id)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data;
}

export async function getRuns(db: Db) {
  const { data, error } = await db.from("search_run").select("*").order("source");
  if (error) throw new Error(error.message);
  return data ?? [];
}

export async function counts(db: Db) {
  const { data, error } = await db.from("search_job_counts").select("*");
  if (error) throw new Error(error.message);
  return data ?? [];
}

// ---------------------------------------------------------------- writing

export async function insertJob(
  db: Db,
  job: {
    source: string;
    sourceId: string | number;
    title: string;
    company?: string | null;
    location?: string | null;
    salary?: string | null;
    url: string;
    description?: string | null;
    postedAt?: string | Date | null;
  },
  { manual = false } = {},
): Promise<number | null> {
  const row = {
    source: job.source,
    source_id: String(job.sourceId),
    dedupe_key: dedupeKey(job.company ?? "", job.title),
    title: job.title.trim(),
    company: job.company?.trim() || null,
    location: job.location?.trim() || null,
    salary: job.salary || null,
    url: job.url,
    description: job.description ? job.description.slice(0, 5000) : null,
    posted_at: new Date(job.postedAt || Date.now()).toISOString(),
    fetched_at: new Date().toISOString(),
    manual,
  };

  // A cross-board duplicate is a skip, not an error — including when the
  // existing row is dismissed, which is the point: dismissing a job has to
  // stop every board from re-adding it.
  if (!manual) {
    const { data: dupe } = await db
      .from("search_job")
      .select("id")
      .eq("dedupe_key", row.dedupe_key)
      .limit(1)
      .maybeSingle();
    if (dupe) return null;
  }

  const { data, error } = await db
    .from("search_job")
    .insert(row)
    .select("id")
    .maybeSingle();

  // 23505 is the (source, source_id) unique constraint: the same posting seen
  // twice in one run, or a run overlapping the previous one. Also a skip.
  if (error) {
    if (error.code === "23505") return null;
    throw new Error(error.message);
  }
  return data?.id ?? null;
}

export async function updateJob(db: Db, id: number, patch: Record<string, unknown>) {
  const fields = Object.fromEntries(
    Object.entries(patch).filter(([k]) => (EDITABLE as readonly string[]).includes(k)),
  );
  if (!Object.keys(fields).length) return getJob(db, id);

  const { data, error } = await db
    .from("search_job")
    .update(fields)
    .eq("id", id)
    .select("*")
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data;
}

/** Soft delete: the row stays so the scraper never re-adds the job. */
export async function dismissJob(db: Db, id: number) {
  const { data, error } = await db
    .from("search_job")
    .update({ status: "dismissed" })
    .eq("id", id)
    .select("id")
    .maybeSingle();
  if (error) throw new Error(error.message);
  return Boolean(data);
}

/** Hard delete, only for manually added jobs — nothing will re-add them. */
export async function deleteJob(db: Db, id: number) {
  const { error } = await db.from("search_job").delete().eq("id", id);
  if (error) throw new Error(error.message);
  return true;
}

// ------------------------------------------------------ scraper bookkeeping

/** Source ids already stored or rejected, so scrapers skip expensive detail fetches. */
export async function getKnownSourceIds(db: Db, source: string): Promise<Set<string>> {
  // Two queries unioned here rather than a SQL UNION, because PostgREST has
  // no way to express one — and both are index lookups on a single column.
  const [stored, rejected] = await Promise.all([
    db.from("search_job").select("source_id").eq("source", source),
    db.from("search_rejected").select("source_id").eq("source", source),
  ]);
  const ids = new Set<string>();
  for (const row of stored.data ?? []) ids.add(String(row.source_id));
  for (const row of rejected.data ?? []) ids.add(String(row.source_id));
  return ids;
}

export async function recordReject(
  db: Db,
  job: { source: string; sourceId: string | number },
  reason: unknown,
) {
  await db.from("search_rejected").upsert(
    {
      source: job.source,
      source_id: String(job.sourceId),
      reason: String(reason).slice(0, 300),
      seen_at: new Date().toISOString(),
    },
    { onConflict: "source,source_id" },
  );
}

export async function recordRun(
  db: Db,
  run: {
    source: string;
    started_at?: string | null;
    finished_at?: string | null;
    fetched?: number | null;
    accepted?: number | null;
    inserted?: number | null;
    error?: string | null;
  },
) {
  await db.from("search_run").upsert(run, { onConflict: "source" });
}

/** Drops old untouched jobs so the table does not grow forever. */
export async function pruneOld(db: Db, days = 30) {
  const cutoff = new Date(Date.now() - days * 864e5).toISOString();
  await db.from("search_rejected").delete().lt("seen_at", cutoff);
  const { data } = await db
    .from("search_job")
    .delete()
    // Dismissed rows are kept deliberately: they are what stops a job being
    // re-added, and pruning them would resurrect everything ever hidden.
    .eq("status", "new")
    .eq("manual", false)
    .lt("posted_at", cutoff)
    .select("id");
  return data?.length ?? 0;
}
